void models_details_c_(){
strcpy(models[0].model_path,"GMI-models/all_sky_dense_model_land.onnx");
printf("model[0] =%s \n",models[0].model_path);
strcpy(models[0].inputs[0].name,"input");
models[0].inputs[0].shape_len=2;
models[0].inputs[0].n_elem=16;
models[0].inputs[0].shape[0]=1;
models[0].inputs[0].shape[1]=16;
models[0].inputs[0].dtype=1;
models[0].input_data[0]=(float *) malloc(sizeof(float)*16);
models[0].num_inputs=1;
models[0].num_outputs=1;
strcpy(models[0].outputs[0].name,"output");
models[0].outputs[0].shape_len=2;
models[0].outputs[0].n_elem=28;
models[0].outputs[0].shape[0]=1;
models[0].outputs[0].shape[1]=28;
models[0].outputs[0].dtype=1;
models[0].output_data[0]=(float *) malloc(sizeof(float)*28);
strcpy(models[1].model_path,"GMI-models/all_sky_dense_model_ocean.onnx");
printf("model[1] =%s \n",models[1].model_path);
strcpy(models[1].inputs[0].name,"input");
models[1].inputs[0].shape_len=2;
models[1].inputs[0].n_elem=16;
models[1].inputs[0].shape[0]=1;
models[1].inputs[0].shape[1]=16;
models[1].inputs[0].dtype=1;
models[1].input_data[0]=(float *) malloc(sizeof(float)*16);
models[1].num_inputs=1;
models[1].num_outputs=1;
strcpy(models[1].outputs[0].name,"output");
models[1].outputs[0].shape_len=2;
models[1].outputs[0].n_elem=28;
models[1].outputs[0].shape[0]=1;
models[1].outputs[0].shape[1]=28;
models[1].outputs[0].dtype=1;
models[1].output_data[0]=(float *) malloc(sizeof(float)*28);
strcpy(models[2].model_path,"GMI-models/dense_decoder_land.onnx");
printf("model[2] =%s \n",models[2].model_path);
strcpy(models[2].inputs[0].name,"enc_output");
models[2].inputs[0].shape_len=2;
models[2].inputs[0].n_elem=4;
models[2].inputs[0].shape[0]=1;
models[2].inputs[0].shape[1]=4;
models[2].inputs[0].dtype=1;
models[2].input_data[0]=(float *) malloc(sizeof(float)*4);
models[2].num_inputs=1;
models[2].num_outputs=1;
strcpy(models[2].outputs[0].name,"dec_output");
models[2].outputs[0].shape_len=2;
models[2].outputs[0].n_elem=11;
models[2].outputs[0].shape[0]=1;
models[2].outputs[0].shape[1]=11;
models[2].outputs[0].dtype=1;
models[2].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[3].model_path,"GMI-models/dense_decoder_ocean.onnx");
printf("model[3] =%s \n",models[3].model_path);
strcpy(models[3].inputs[0].name,"enc_output");
models[3].inputs[0].shape_len=2;
models[3].inputs[0].n_elem=4;
models[3].inputs[0].shape[0]=1;
models[3].inputs[0].shape[1]=4;
models[3].inputs[0].dtype=1;
models[3].input_data[0]=(float *) malloc(sizeof(float)*4);
models[3].num_inputs=1;
models[3].num_outputs=1;
strcpy(models[3].outputs[0].name,"dec_output");
models[3].outputs[0].shape_len=2;
models[3].outputs[0].n_elem=11;
models[3].outputs[0].shape[0]=1;
models[3].outputs[0].shape[1]=11;
models[3].outputs[0].dtype=1;
models[3].output_data[0]=(float *) malloc(sizeof(float)*11);
strcpy(models[4].model_path,"GMI-models/dense_encoder_land.onnx");
printf("model[4] =%s \n",models[4].model_path);
strcpy(models[4].inputs[0].name,"input");
models[4].inputs[0].shape_len=2;
models[4].inputs[0].n_elem=11;
models[4].inputs[0].shape[0]=1;
models[4].inputs[0].shape[1]=11;
models[4].inputs[0].dtype=1;
models[4].input_data[0]=(float *) malloc(sizeof(float)*11);
models[4].num_inputs=1;
models[4].num_outputs=1;
strcpy(models[4].outputs[0].name,"enc_output");
models[4].outputs[0].shape_len=2;
models[4].outputs[0].n_elem=4;
models[4].outputs[0].shape[0]=1;
models[4].outputs[0].shape[1]=4;
models[4].outputs[0].dtype=1;
models[4].output_data[0]=(float *) malloc(sizeof(float)*4);
strcpy(models[5].model_path,"GMI-models/dense_encoder_ocean.onnx");
printf("model[5] =%s \n",models[5].model_path);
strcpy(models[5].inputs[0].name,"input");
models[5].inputs[0].shape_len=2;
models[5].inputs[0].n_elem=11;
models[5].inputs[0].shape[0]=1;
models[5].inputs[0].shape[1]=11;
models[5].inputs[0].dtype=1;
models[5].input_data[0]=(float *) malloc(sizeof(float)*11);
models[5].num_inputs=1;
models[5].num_outputs=1;
strcpy(models[5].outputs[0].name,"enc_output");
models[5].outputs[0].shape_len=2;
models[5].outputs[0].n_elem=4;
models[5].outputs[0].shape[0]=1;
models[5].outputs[0].shape[1]=4;
models[5].outputs[0].dtype=1;
models[5].output_data[0]=(float *) malloc(sizeof(float)*4);
strcpy(models[6].model_path,"GMI-models/x_1d_dense_model_land.onnx");
printf("model[6] =%s \n",models[6].model_path);
strcpy(models[6].inputs[0].name,"input");
models[6].inputs[0].shape_len=2;
models[6].inputs[0].n_elem=16;
models[6].inputs[0].shape[0]=1;
models[6].inputs[0].shape[1]=16;
models[6].inputs[0].dtype=1;
models[6].input_data[0]=(float *) malloc(sizeof(float)*16);
models[6].num_inputs=1;
models[6].num_outputs=1;
strcpy(models[6].outputs[0].name,"output");
models[6].outputs[0].shape_len=2;
models[6].outputs[0].n_elem=62;
models[6].outputs[0].shape[0]=1;
models[6].outputs[0].shape[1]=62;
models[6].outputs[0].dtype=1;
models[6].output_data[0]=(float *) malloc(sizeof(float)*62);
strcpy(models[7].model_path,"GMI-models/x_1d_dense_model_ocean.onnx");
printf("model[7] =%s \n",models[7].model_path);
strcpy(models[7].inputs[0].name,"input");
models[7].inputs[0].shape_len=2;
models[7].inputs[0].n_elem=16;
models[7].inputs[0].shape[0]=1;
models[7].inputs[0].shape[1]=16;
models[7].inputs[0].dtype=1;
models[7].input_data[0]=(float *) malloc(sizeof(float)*16);
models[7].num_inputs=1;
models[7].num_outputs=1;
strcpy(models[7].outputs[0].name,"output");
models[7].outputs[0].shape_len=2;
models[7].outputs[0].n_elem=62;
models[7].outputs[0].shape[0]=1;
models[7].outputs[0].shape[1]=62;
models[7].outputs[0].dtype=1;
models[7].output_data[0]=(float *) malloc(sizeof(float)*62);
strcpy(models[8].model_path,"GMI-models/xdense_model_land.onnx");
printf("model[8] =%s \n",models[8].model_path);
strcpy(models[8].inputs[0].name,"input");
models[8].inputs[0].shape_len=2;
models[8].inputs[0].n_elem=16;
models[8].inputs[0].shape[0]=1;
models[8].inputs[0].shape[1]=16;
models[8].inputs[0].dtype=1;
models[8].input_data[0]=(float *) malloc(sizeof(float)*16);
models[8].num_inputs=1;
models[8].num_outputs=1;
strcpy(models[8].outputs[0].name,"output");
models[8].outputs[0].shape_len=2;
models[8].outputs[0].n_elem=8;
models[8].outputs[0].shape[0]=1;
models[8].outputs[0].shape[1]=8;
models[8].outputs[0].dtype=1;
models[8].output_data[0]=(float *) malloc(sizeof(float)*8);
strcpy(models[9].model_path,"GMI-models/xdense_model_ocean.onnx");
printf("model[9] =%s \n",models[9].model_path);
strcpy(models[9].inputs[0].name,"input");
models[9].inputs[0].shape_len=2;
models[9].inputs[0].n_elem=16;
models[9].inputs[0].shape[0]=1;
models[9].inputs[0].shape[1]=16;
models[9].inputs[0].dtype=1;
models[9].input_data[0]=(float *) malloc(sizeof(float)*16);
models[9].num_inputs=1;
models[9].num_outputs=1;
strcpy(models[9].outputs[0].name,"output");
models[9].outputs[0].shape_len=2;
models[9].outputs[0].n_elem=8;
models[9].outputs[0].shape[0]=1;
models[9].outputs[0].shape[1]=8;
models[9].outputs[0].dtype=1;
models[9].output_data[0]=(float *) malloc(sizeof(float)*8);
}
